### Add expense
POST localhost:80/api/v1/expenses
Content-Type: application/json

{
  "date": "2024-01-01",
  "title": "Наушники",
  "description": "Запасная модель",
  "catalog":  "техника",
  "cost": 1000
}

### List expenses
GET localhost:80/api/v1/expenses?limit=10&offset=0&dateFrom=2023-01-01&dateTo=2025-01-01

### Delete expenses
DELETE localhost:80/api/v1/expenses?ids=1,2